### ISSUE TITLE
Depend on the latest matb33:collection-hooks v1.0.1

### ISSUE THREAD

**Issue by droka** [jalik/meteor-jalik-ufs#145]
Currently the package has explicit dependency on matb33:collection-hooks@0.9.0
Meanwhile in collection-hooks 1.0 some bugs were fixed, which prevented collection-hooks running properly along with other packages (like collection-behaviours).
Is it possible to remove the explicit dependency on 0.9.0, and just use the newest version? 
I can send PR.
That is unless there is a reason behind depending on 0.9.0 specifically.

**Comment by jalik** [comment]
@droka I have published the 1.0.1 version which uses the latest version of matb33:collection-hooks.
